# Cloudflare Pages configuration
name = "ngo-going-out"
pages_build_output_dir = "web"
compatibility_date = "2024-10-01"

# D1 database binding for Pages Functions
[[d1_databases]]
binding = "database"
database_name = "ngo_going_out"
database_id = "37d806ec-8aa0-462c-ba35-aa998a1005f6"
